PACKAGE_NAME="usbled-standalone"
PACKAGE_VERSION="1.1.1-pre.0"

BUILT_MODULE_NAME[0]="usbled"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"

MAKE[0]="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules"
CLEAN="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"