---
name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: sudo cp /sys/kernel/btf/vmlinux /usr/lib/modules/$(uname -r)/build
      - run: sudo make deps
      - run: make clean build
      - run: sudo make install uninstall
      - run: sudo make deps-deb
      - run: make clean
      - run: sudo make build-deb install-deb uninstall-deb
