---
name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install dwarves
      - run: sudo cp /sys/kernel/btf/vmlinux /usr/lib/modules/$(shell uname -r)/build
      - run: make ci
