---
name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install dwarves
      - run: sudo cp /sys/kernel/btf/vmlinux /usr/lib/modules/$(uname -r)/build
      - run: make ci
      - run: sudo make install
