---
name: Publish
'on':
  push:
    tags:
      - '*'
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - run: sudo make deps-deb build-deb install-deb uninstall-deb
      - run: make publish-deb
        env:
          GITHUB_TOKEN: ${{ secrets.STUDIO_GITHUB_TOKEN }}
